export enum LoanType {
  PERSONAL_USE = 'PERSONAL_USE',
  BUSINESS_EXPANSION = 'BUSINESS_EXPANSION',
  EQUIPMENT_FINANCING = 'EQUIPMENT_FINANCING',
  WORKING_CAPITAL = 'WORKING_CAPITAL',
  DEBT_CONSOLIDATION = 'DEBT_CONSOLIDATION',
}

